openapi: 3.0.3
info:
  title: Aloy API
  version: 0.1.0
paths:
  /health:
    get:
      operationId: getHealth
      responses:
        "200":
          description: API is ready to accept requests.

